<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>mason</string>
    <key>scopeName</key>
    <string>source.mason</string>
    <key>fileTypes</key>
    <array>
      <string>ms</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>string</string>
        <key>begin</key>
        <string>^\t{0}[^\t&quot;]*&quot;$</string>
        <key>end</key>
        <string>^\t{,0}(?=[^\t])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#([^`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#\(([^\)]*)\)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>string</string>
        <key>begin</key>
        <string>^\t{1}[^\t&quot;]*&quot;$</string>
        <key>end</key>
        <string>^\t{,1}(?=[^\t])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#([^`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#\(([^\)]*)\)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>string</string>
        <key>begin</key>
        <string>^\t{2}[^\t&quot;]*&quot;$</string>
        <key>end</key>
        <string>^\t{,2}(?=[^\t])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#([^`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#\(([^\)]*)\)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>string</string>
        <key>begin</key>
        <string>^\t{3}[^\t&quot;]*&quot;$</string>
        <key>end</key>
        <string>^\t{,3}(?=[^\t])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#([^`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#\(([^\)]*)\)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>string</string>
        <key>begin</key>
        <string>^\t{4}[^\t&quot;]*&quot;$</string>
        <key>end</key>
        <string>^\t{,4}(?=[^\t])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#([^`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#\(([^\)]*)\)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>string</string>
        <key>begin</key>
        <string>^\t{5}[^\t&quot;]*&quot;$</string>
        <key>end</key>
        <string>^\t{,5}(?=[^\t])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#([^`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#\(([^\)]*)\)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>string</string>
        <key>begin</key>
        <string>^\t{6}[^\t&quot;]*&quot;$</string>
        <key>end</key>
        <string>^\t{,6}(?=[^\t])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#([^`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#\(([^\)]*)\)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>string</string>
        <key>begin</key>
        <string>^\t{7}[^\t&quot;]*&quot;$</string>
        <key>end</key>
        <string>^\t{,7}(?=[^\t])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#([^`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#\(([^\)]*)\)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>string</string>
        <key>begin</key>
        <string>^\t{8}[^\t&quot;]*&quot;$</string>
        <key>end</key>
        <string>^\t{,8}(?=[^\t])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#([^`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#\(([^\)]*)\)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>string</string>
        <key>begin</key>
        <string>^\t{9}[^\t&quot;]*&quot;$</string>
        <key>end</key>
        <string>^\t{,9}(?=[^\t])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#([^`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#\(([^\)]*)\)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>string</string>
        <key>begin</key>
        <string>`</string>
        <key>end</key>
        <string>`(g?i?m?y?)|(.(?=\n))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#([^`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#\(([^\)]*)\)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
        </array>
        <key>endCaptures</key>
        <dict/>
      </dict>
      <dict>
        <key>name</key>
        <string>string</string>
        <key>begin</key>
        <string>&quot;</string>
        <key>end</key>
        <string>&quot;|(.(?=\n))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#([^`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>#\(([^\)]*)\)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
          </dict>
        </array>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>string</string>
        <key>match</key>
        <string>&apos;[^`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;]+</string>
      </dict>
      <dict>
        <key>name</key>
        <string>comment</string>
        <key>match</key>
        <string>\|(\||\s).*</string>
      </dict>
      <dict>
        <key>name</key>
        <string>comment</string>
        <key>match</key>
        <string>^\s*(region)[^\n]*\n</string>
      </dict>
      <dict>
        <key>name</key>
        <string>comment</string>
        <key>match</key>
        <string>^\s*(todo)[^\n]*\n</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>punctuation.section.embedded</string>
        <key>match</key>
        <string>[\(\[\]\)\{\}]</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric</string>
        <key>match</key>
        <string>-?0(b|o|x)[0-9a-f]+</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric</string>
        <key>match</key>
        <string>-?\d+(\.\d+)?</string>
      </dict>
      <dict>
        <key>name</key>
        <string>support.type</string>
        <key>match</key>
        <string>(:)[^\s=]+</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>comment</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword</string>
        <key>match</key>
        <string>\.</string>
      </dict>
      <dict>
        <key>name</key>
        <string>variable</string>
        <key>begin</key>
        <string>((\*|\$)?\!?\\)</string>
        <key>end</key>
        <string>\n</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>support.type</string>
            <key>match</key>
            <string>(:)\S+</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>\|\s.*</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>comment</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>support.type</string>
        <key>match</key>
        <string>&amp;</string>
      </dict>
      <dict>
        <key>name</key>
        <string>entity.other.attribute-name</string>
        <key>match</key>
        <string>([^\s\.:]+)((:)([^\s\.]+))?((\.)|\s(=))\s</string>
        <key>captures</key>
        <dict/>
      </dict>
      <dict>
        <key>name</key>
        <string>invalid.illegal</string>
        <key>match</key>
        <string>[#^\\&apos;;,]</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.language</string>
        <key>match</key>
        <string>[^`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;]+(_)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>invalid.illegal</string>
        <key>match</key>
        <string>(!|&lt;|&lt;-|&gt;|actor|any|arguments|bignum|boolean|complex|continue|data|decimal|decimal128|decimal32|decimal64|declare|del?|delete|do-until|do-while|enum|eval|final|flags|float|float128|float32|float64|from|implements|implicit|in|instanceof|int|int16|int32|int64|int8|interface|is|macro|meta|mixed|move|mut|native|number|object|on|operator|out|package|private|protected|ptr|public|pure|rational|readonly|return|sealed|send|shared|sizeof|string|struct|symbol|synchronized|throws|to|transient|type|typeof|uint|uint16|uint32|uint64|uint8|until|use|void|volatile|while)(?=[`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;])</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword</string>
        <key>match</key>
        <string>(!\|\$|\$!\|\$\|\$for|%|&amp;|&apos;|\*|\*!\|\*\*|\*\|\+|-|-&gt;|\/|&lt;\?|&gt;\?|@for|_|abstract|and|as|assert|break|built|case|catch|class|cond|construct|debugger|del|do|else|except|extends|false|finally|for|forbid|get|if|ignore|import|import!|import~|my|name|neg|new|not|null|of|or|override|pass|pipe|poly|region|set|static|super|switch|throw|todo|trait|trait!|true|try|undefined|unless|virtual|with|yield|yield\*|~|this|==?\?|&lt;=\?|&gt;=\?|:=)(?=[`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;])</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword</string>
        <key>match</key>
        <string>~</string>
      </dict>
      <dict>
        <key>name</key>
        <string>none</string>
        <key>match</key>
        <string>[^`&amp;()\[\]{}|:&quot;.\s#^\\;,&apos;]+</string>
      </dict>
    </array>
  </dict>
</plist>